CREATE DATABASE CAFERESTAURANT
GO
USE CAFERESTAURANT
GO

CREATE TABLE TABLESERVE
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'Bàn chưa có tên',
	STATUS NVARCHAR(100) NOT NULL DEFAULT N'Trống'
)
GO

CREATE TABLE FOODCAGETORY
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'Chưa có tên',
)
GO

CREATE TABLE FOOD
(
	ID INT IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	PRICE FLOAT NOT NULL DEFAULT 0,
	IDCAGETORY INT NOT NULL,
	FOREIGN KEY (IDCAGETORY) REFERENCES dbo.FOODCAGETORY(ID)
)
GO

CREATE TABLE BILL
(
	ID INT IDENTITY PRIMARY KEY,
	DAYCHECKIN DATE NOT NULL DEFAULT GETDATE(),
	DAYCHECKOUT DATE,
	IDTABLE INT NOT NULL,
	STATUS INT NOT NULL DEFAULT 0,
	FOREIGN KEY (IDTABLE) REFERENCES dbo.TABLESERVE(ID)
)
GO

CREATE TABLE BILLINFO
(
	ID INT IDENTITY PRIMARY KEY,
	IDBILL INT NOT NULL,
	IDFOOD INT NOT NULL,
	count INT NOT NULL DEFAULT 0,
	
	FOREIGN KEY (IDBILL) REFERENCES dbo.Bill(ID),
	FOREIGN KEY (IDFOOD) REFERENCES dbo.Food(ID)
)
GO